=== danilimones-03/ASIR/medicamentos.dtd
<!ELEMENT medicamentos (medicamento+)>

<!ELEMENT medicamento (nombre,administracion,cantidaddosis)>
<!ELEMENT nombre (generico,comercial+)>
    <!ELEMENT generico (#PCDATA)>
    <!ELEMENT comercial (#PCDATA)>
<!ELEMENT administracion (#PCDATA)>
         
 <!ELEMENT cantidaddosis (#PCDATA)>

<!ATTLIST nombre id ID #REQUIRED>
<!ATTLIST administracion tipo (Intramuscular|oral) #REQUIRED>

=== danilimones-03/ASIR/medicamentos.xml
<?xml version="1.0"?>
<!DOCTYPE medicamentos SYSTEM "medicamentos.dtd">
<!-- Esta es la estructura del medicamento copiar para poner otro-->

<medicamentos>
    <medicamento>
    <nombre id="ID1">
        <generico>Acido acetilsalicilico</generico>
        <comercial>Aspirina</comercial>

    </nombre>
    
<!-- Intramuscular y oral-->
    <administracion tipo="oral">4h o 6h</administracion>

    

    <cantidaddosis>500mg</cantidaddosis>
    
    
</medicamento>
    
<medicamento>
    <nombre id="ID2">
        <generico>Heparina </generico>
        <comercial>Inhepar</comercial>

    </nombre>
    
<!-- Intramuscular y oral-->
    <administracion tipo="Intramuscular">12h</administracion>

    

    <cantidaddosis>80 UI/kg</cantidaddosis>
    
    
</medicamento>

</medicamentos>
