=== danilimones-03/ASIR/EJERCICIOS PARA EXAMEN/resumen.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="resumenes">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="ConjuntoSimples">
          <xs:complexType>
            <xs:all>
              <xs:element name="sinAtributo" type="xs:string"/>
              <!-- Tipos: integer, string, date, etc-->
              <xs:element name="sinAtributoTipoSimple" type="xs:date"/>
                      <!-- Tipos: integer, string, date, etc-->
              <xs:element name="sinAtributoTipoDefinido" type="ciudad"/>

            </xs:all>
          </xs:complexType>
        </xs:element>

        <xs:element name="ConjuntoComplejos">
          <xs:complexType>
            <xs:all>
                <!-- Sin atributos con tipos base-->
                <!-- -->
              <xs:element name="Elemento1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="subElemento1" type="xs:string"/>
                    <xs:element name="subElemento2" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="Elemento2">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="subElemento1" type="xs:string"/>
                    <xs:element name="subElemento2" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:integer"/>
                </xs:complexType>
              </xs:element>
            
              <xs:element name="Elemento3">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="subElemento1" type="xs:string"/>
                    <xs:element name="subElemento2" type="direccion"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="Elemento4">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="subElemento1" type="xs:string"/>
                    <xs:element name="subElemento2" type="ciudad2"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:integer"/>
                </xs:complexType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
<!-- Ejercicio numerico-->
        <xs:element name="telefono">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="([+][0-9]{11})*"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
<!-- Ejercicio mixto-->
        <xs:element name="contrasena">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="5"/>
              <xs:maxLength value="8"/>
              <xs:pattern value="[a-zA-Z0-9]{8}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <!-- Ejercicio choise/all/sequence-->
        <xs:choice>
        <xs:element name="Audi" type="modeloAudi" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="Seat" type="modeloSeat"/>
        </xs:choice>
        <!-- Ejercicio sequence-->
        <xs:element name="Secuencia">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Nombre" type="xs:string"/>
                <xs:element name="Apellidos" type="xs:string"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <!-- Ejercicio all-->
     <!-- Para este ejercicio voy a describir varios elementos -->
     <xs:element name="Coches">
      <xs:complexType>
        <xs:all>
          <xs:element name="Mercedes">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Tipo" type="xs:string"/>
                <xs:element name="Color" type="colores"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>

          <xs:element name="Toyota">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Tipo" type="xs:string"/>
                <xs:element name="Color" type="colores"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        
          <xs:element name="BMW">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Tipo" type="xs:string"/>
                <xs:element name="Color" type="colores"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>

        </xs:all>
      </xs:complexType>
     </xs:element>
        </xs:sequence>

    </xs:complexType>
  </xs:element>

<!-- Definiciones-->
  <!-- Tipo "Direccion"-->
  <xs:simpleType name="ciudad">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Sevilla"/>
      <xs:enumeration value="Cordoba"/>
      <xs:enumeration value="Malaga"/>
      <xs:enumeration value="Granada"/>
      <xs:enumeration value="Huelva"/>
      <xs:enumeration value="Jaen"/>
      <xs:enumeration value="Cadiz"/>
      <xs:enumeration value="Almeria"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="direccion">
    <xs:sequence>
      <xs:element name="localicad" type="xs:string"/>
      <xs:element name="CP" type="xs:integer"/>
      <xs:element name="ciudad" type="ciudad"/>
    </xs:sequence>
  </xs:complexType>
    
  <xs:complexType name="ciudad2">
    <xs:sequence>
      <xs:element name="localidad" type="xs:string"/>
      <xs:element name="CP" type="xs:integer"/>
      <xs:element name="ciudad" type="ciudad"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="modeloAudi">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Rojo"/>
      <xs:enumeration value="Verde"/>
      <xs:enumeration value="Azul"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="modeloSeat">
    <xs:restriction base="xs:string">
      <xs:enumeration value="1005"/>
      <xs:enumeration value="2003"/>
      <xs:enumeration value="3008"/>
    </xs:restriction>
  </xs:simpleType>

    
  <xs:simpleType name="colores">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Negro"/>
      <xs:enumeration value="Azul"/>
      <xs:enumeration value="Blanco"/>
    </xs:restriction>
  </xs:simpleType>


</xs:schema>

=== danilimones-03/ASIR/EJERCICIOS PARA EXAMEN/resumen.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<resumenes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resumen.xsd">

  <ConjuntoSimples>
    <sinAtributo>Daniel</sinAtributo>
    <sinAtributoTipoSimple>2004-02-22</sinAtributoTipoSimple>
    <sinAtributoTipoDefinido>Sevilla</sinAtributoTipoDefinido>
  </ConjuntoSimples>

<ConjuntoComplejos>
  <Elemento1>
    <subElemento1></subElemento1>
    <subElemento2></subElemento2>
  </Elemento1>

  <Elemento2 id="0">
    <subElemento1></subElemento1>
    <subElemento2></subElemento2>
  </Elemento2>

  <Elemento3>
    <subElemento1></subElemento1>
    <subElemento2>
      <localicad></localicad>
      <CP>41400</CP>
      <ciudad>Sevilla</ciudad>
    </subElemento2>
  </Elemento3>

  <Elemento4 id="0">
    <subElemento1></subElemento1>
    <subElemento2>
      <localidad></localidad>
      <CP>41400</CP>
      <ciudad>Sevilla</ciudad>
    </subElemento2>
      
    
  </Elemento4>

</ConjuntoComplejos>

<telefono></telefono>

<contrasena>Usuario1</contrasena>

<Audi>Verde</Audi>

<Secuencia>
<Nombre></Nombre>
<Apellidos></Apellidos>

</Secuencia>

<Coches>
<BMW>
  <Tipo></Tipo>
  <Color>Azul</Color>
  
</BMW>
<Mercedes>
  <Tipo></Tipo>
  <Color>Blanco</Color>
</Mercedes>
<Toyota>
  <Tipo></Tipo>
  <Color>Negro</Color>
</Toyota>

</Coches>

</resumenes>
